### ISSUE TITLE
I can't build when I use it

### ISSUE THREAD

**Issue by www-xu** [shershen08/emoji-vue#11]
Is caused by UglifyJs，like that
```
ERROR in static/js/vendor.336cc80736d2b58efdd2.js from UglifyJs
undefined
  Build failed with errors.
```

The log is as follows
```
13 verbose stack Error: picture-web@1.0.0 build: `node build/build.js`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (D:\Program Files\Nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:301:16)
13 verbose stack     at EventEmitter.emit (events.js:182:13)
13 verbose stack     at ChildProcess.<anonymous> (D:\Program Files\Nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:182:13)
13 verbose stack     at maybeClose (internal/child_process.js:962:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:251:5)
14 verbose pkgid picture-web@1.0.0
15 verbose cwd C:\Users\wangx\Projects\picture\picture-web
16 verbose Windows_NT 6.1.7601
17 verbose argv "D:\\Program Files\\Nodejs\\node.exe" "D:\\Program Files\\Nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "build"
18 verbose node v10.14.2
19 verbose npm  v6.4.1
```
thanks

**Comment by shershen08** [comment]
this doesn't give much actionable details unfortunately.

 could you tell me which version of `node` and `npm` you use?
ideal would be if could provide minimum reducible error with the repo containing package.json and a webpack config

**Comment by www-xu** [comment]
Hello, I don't know what's going on, but now I can build successfully, thank you.

**Comment by shershen08** [comment]
Great to hear,
Usually reinstall dependences and check the valid npm/node version helps
